# generated by "rails generate scaffold post title:string content:text"

class CreatePosts < ActiveRecord::Migration[7.0]
  def change
    create_table :posts do |t|
      t.string :title
      t.text :content

      # rails adds by default a set of timestamps for created at and update at
      t.timestamps
    end
  end
end
